disabled_rules:
  - type_body_length
  - file_length
included:
    - Sources
    - Tests
line_length: 200
identifier_name:
  min-length: 4
  max_length: 60
  excluded:
    - i
    - id
    - tx
    - trx
    - x